// All 60 Riviera Select Amenities Data matching public/Amenity/amenity-img/

export const AMENITIES_LIST = [
  {
    id: "waiting-lounge",
    label: "Waiting Lounge",
    icon: "/Amenity/amenity-icon/waiting-lounge.svg",
    photo: "/Amenity/amenity-img/waiting_lounge.svg",
    img: "/Amenity/amenity-img/waiting_lounge.svg",
  },
  {
    id: "yoga-aerobics",
    label: "Yoga & Aerobics",
    icon: "/Amenity/amenity-icon/yoga-aerobics.svg",
    photo: "/Amenity/amenity-img/yoga.jpg",
    img: "/Amenity/amenity-img/yoga.jpg",
  },
  {
    id: "gymnasium",
    label: "Gymnasium",
    icon: "/Amenity/amenity-icon/gymnasium.svg",
    photo: "/Amenity/amenity-img/gym.jpg",
    img: "/Amenity/amenity-img/gym.jpg",
  },
  {
    id: "spa",
    label: "Spa",
    icon: "/Amenity/amenity-icon/spa.svg",
    photo: "/Amenity/amenity-img/spa.jpg",
    img: "/Amenity/amenity-img/spa.jpg",
  },
  {
    id: "social-lounge",
    label: "Social Lounge",
    icon: "/Amenity/amenity-icon/social-lounge.svg",
    photo: "/Amenity/amenity-img/social_lounge.jpg",
    img: "/Amenity/amenity-img/social_lounge.jpg",
  },
  {
    id: "salon",
    label: "Salon",
    icon: "/Amenity/amenity-icon/salon.svg",
    photo: "/Amenity/amenity-img/salon.jpg",
    img: "/Amenity/amenity-img/salon.jpg",
  },
  {
    id: "mini-home-theatre",
    label: "Mini Home Theater",
    icon: "/Amenity/amenity-icon/mini-home-theatre.svg",
    photo: "/Amenity/amenity-img/mini_home_theatre.jpg",
    img: "/Amenity/amenity-img/mini_home_theatre.jpg",
  },
  {
    id: "swimming-pool",
    label: "Swimming Pool",
    icon: "/Amenity/amenity-icon/swimming-pool.svg",
    photo: "/Amenity/amenity-img/swimming_pool.jpg",
    img: "/Amenity/amenity-img/swimming_pool.jpg",
  },
  {
    id: "kids-play-area",
    label: "Kids Play Area",
    icon: "/Amenity/amenity-icon/kids-play-area.svg",
    photo: "/Amenity/amenity-img/kids_play_area.jpg",
    img: "/Amenity/amenity-img/kids_play_area.jpg",
  },
  {
    id: "indoor-games",
    label: "Indoor Games",
    icon: "/Amenity/amenity-icon/indoor-games.svg",
    photo: "/Amenity/amenity-img/indoor_games.jpg",
    img: "/Amenity/amenity-img/indoor_games.jpg",
  },
  {
    id: "outdoor-games",
    label: "Outdoor Games",
    icon: "/Amenity/amenity-icon/outdoor-games.svg",
    photo: "/Amenity/amenity-img/outoor_games.jpg",
    img: "/Amenity/amenity-img/outoor_games.jpg",
  },
  {
    id: "party-hall",
    label: "Party Hall",
    icon: "/Amenity/amenity-icon/party-hall.svg",
    photo: "/Amenity/amenity-img/party_hall.jpg",
    img: "/Amenity/amenity-img/party_hall.jpg",
  },
  {
    id: "banquet-hall",
    label: "Banquet Hall",
    icon: "/Amenity/amenity-icon/banquet-hall.svg",
    photo: "/Amenity/amenity-img/banquet_hall.jpg",
    img: "/Amenity/amenity-img/banquet_hall.jpg",
  },
  {
    id: "multipurpose-hall",
    label: "Multipurpose Hall",
    icon: "/Amenity/amenity-icon/multipurpose-hall.svg",
    photo: "/Amenity/amenity-img/multipurpose_hall.jpg",
    img: "/Amenity/amenity-img/multipurpose_hall.jpg",
  },
  {
    id: "clubhouse",
    label: "Clubhouse",
    icon: "/Amenity/amenity-icon/clubhouse.svg",
    photo: "/Amenity/amenity-img/clubhouse.jpg",
    img: "/Amenity/amenity-img/clubhouse.jpg",
  },
  {
    id: "library",
    label: "Library",
    icon: "/Amenity/amenity-icon/library.svg",
    photo: "/Amenity/amenity-img/library.jpg",
    img: "/Amenity/amenity-img/library.jpg",
  },
  {
    id: "co-working-space",
    label: "Co-Working Space",
    icon: "/Amenity/amenity-icon/co-working-space.svg",
    photo: "/Amenity/amenity-img/coworking_space.jpg",
    img: "/Amenity/amenity-img/coworking_space.jpg",
  },
  {
    id: "business-lounge",
    label: "Business Lounge",
    icon: "/Amenity/amenity-icon/business-lounge.svg",
    photo: "/Amenity/amenity-img/business_lounge.jpg",
    img: "/Amenity/amenity-img/business_lounge.jpg",
  },
  {
    id: "meeting-room",
    label: "Meeting Room",
    icon: "/Amenity/amenity-icon/meeting-room.svg",
    photo: "/Amenity/amenity-img/meeting_room.jpg",
    img: "/Amenity/amenity-img/meeting_room.jpg",
  },
  {
    id: "cafe",
    label: "Café",
    icon: "/Amenity/amenity-icon/cafe.svg",
    photo: "/Amenity/amenity-img/caf.jpg",
    img: "/Amenity/amenity-img/caf.jpg",
  },
  {
    id: "restaurant",
    label: "Restaurant",
    icon: "/Amenity/amenity-icon/restaurant.svg",
    photo: "/Amenity/amenity-img/restaurant.jpg",
    img: "/Amenity/amenity-img/restaurant.jpg",
  },
  {
    id: "juice-bar",
    label: "Juice Bar",
    icon: "/Amenity/amenity-icon/juice-bar.svg",
    photo: "/Amenity/amenity-img/juice_bar.jpg",
    img: "/Amenity/amenity-img/juice_bar.jpg",
  },
  {
    id: "rooftop-lounge",
    label: "Rooftop Lounge",
    icon: "/Amenity/amenity-icon/rooftop-lounge.svg",
    photo: "/Amenity/amenity-img/rooftop_lounge.jpg",
    img: "/Amenity/amenity-img/rooftop_lounge.jpg",
  },
  {
    id: "sky-garden",
    label: "Sky Garden",
    icon: "/Amenity/amenity-icon/sky-garden.svg",
    photo: "/Amenity/amenity-img/sky_garden.jpg",
    img: "/Amenity/amenity-img/sky_garden.jpg",
  },
  {
    id: "terrace-garden",
    label: "Terrace Garden",
    icon: "/Amenity/amenity-icon/terrace-garden.svg",
    photo: "/Amenity/amenity-img/terrace_garden.jpg",
    img: "/Amenity/amenity-img/terrace_garden.jpg",
  },
  {
    id: "landscaped-garden",
    label: "Landscaped Garden",
    icon: "/Amenity/amenity-icon/landscaped-garden.svg",
    photo: "/Amenity/amenity-img/landscaped_garden.jpg",
    img: "/Amenity/amenity-img/landscaped_garden.jpg",
  },
  {
    id: "walking-track",
    label: "Walking Track",
    icon: "/Amenity/amenity-icon/walking-track.svg",
    photo: "/Amenity/amenity-img/walking_track.jpg",
    img: "/Amenity/amenity-img/walking_track.jpg",
  },
  {
    id: "jogging-track",
    label: "Jogging Track",
    icon: "/Amenity/amenity-icon/jogging-track.svg",
    photo: "/Amenity/amenity-img/jogging_track.jpg",
    img: "/Amenity/amenity-img/jogging_track.jpg",
  },
  {
    id: "cycling-track",
    label: "Cycling Track",
    icon: "/Amenity/amenity-icon/cycling-track.svg",
    photo: "/Amenity/amenity-img/cycling_track.jpg",
    img: "/Amenity/amenity-img/cycling_track.jpg",
  },
  {
    id: "meditation-area",
    label: "Meditation Area",
    icon: "/Amenity/amenity-icon/meditation-area.svg",
    photo: "/Amenity/amenity-img/meditation_area.jpg",
    img: "/Amenity/amenity-img/meditation_area.jpg",
  },
  {
    id: "fitness-studio",
    label: "Fitness Studio",
    icon: "/Amenity/amenity-icon/fitness-studio.svg",
    photo: "/Amenity/amenity-img/fitness_studio.jpg",
    img: "/Amenity/amenity-img/fitness_studio.jpg",
  },
  {
    id: "steam-room",
    label: "Steam Room",
    icon: "/Amenity/amenity-icon/steam-room.svg",
    photo: "/Amenity/amenity-img/steam_room.jpg",
    img: "/Amenity/amenity-img/steam_room.jpg",
  },
  {
    id: "sauna",
    label: "Sauna",
    icon: "/Amenity/amenity-icon/sauna.svg",
    photo: "/Amenity/amenity-img/sauna.jpg",
    img: "/Amenity/amenity-img/sauna.jpg",
  },
  {
    id: "jacuzzi",
    label: "Jacuzzi",
    icon: "/Amenity/amenity-icon/jacuzzi.svg",
    photo: "/Amenity/amenity-img/jacuzzi.jpg",
    img: "/Amenity/amenity-img/jacuzzi.jpg",
  },
  {
    id: "children-s-pool",
    label: "Children's Pool",
    icon: "/Amenity/amenity-icon/children-s-pool.svg",
    photo: "/Amenity/amenity-img/childrens_pool.jpg",
    img: "/Amenity/amenity-img/childrens_pool.jpg",
  },
  {
    id: "senior-citizen-area",
    label: "Senior Citizen Area",
    icon: "/Amenity/amenity-icon/senior-citizen-area.svg",
    photo: "/Amenity/amenity-img/senior_citizen_area.jpg",
    img: "/Amenity/amenity-img/senior_citizen_area.jpg",
  },
  {
    id: "pet-park",
    label: "Pet Park",
    icon: "/Amenity/amenity-icon/pet-park.svg",
    photo: "/Amenity/amenity-img/pet_park.jpg",
    img: "/Amenity/amenity-img/pet_park.jpg",
  },
  {
    id: "bbq-area",
    label: "BBQ Area",
    icon: "/Amenity/amenity-icon/bbq-area.svg",
    photo: "/Amenity/amenity-img/bbq_area.jpg",
    img: "/Amenity/amenity-img/bbq_area.jpg",
  },
  {
    id: "outdoor-seating",
    label: "Outdoor Seating",
    icon: "/Amenity/amenity-icon/outdoor-seating.svg",
    photo: "/Amenity/amenity-img/outdoor_seating.jpg",
    img: "/Amenity/amenity-img/outdoor_seating.jpg",
  },
  {
    id: "gazebo",
    label: "Gazebo",
    icon: "/Amenity/amenity-icon/gazebo.svg",
    photo: "/Amenity/amenity-img/gazebo.jpg",
    img: "/Amenity/amenity-img/gazebo.jpg",
  },
  {
    id: "amphitheatre",
    label: "Amphitheatre",
    icon: "/Amenity/amenity-icon/amphitheatre.svg",
    photo: "/Amenity/amenity-img/amphitheatre.jpg",
    img: "/Amenity/amenity-img/amphitheatre.jpg",
  },
  {
    id: "cricket-practice-area",
    label: "Cricket Practice Area",
    icon: "/Amenity/amenity-icon/cricket-practice-area.svg",
    photo: "/Amenity/amenity-img/cricket.jpg",
    img: "/Amenity/amenity-img/cricket.jpg",
  },
  {
    id: "basketball-court",
    label: "Basketball Court",
    icon: "/Amenity/amenity-icon/basketball-court.svg",
    photo: "/Amenity/amenity-img/basketball_court.jpg",
    img: "/Amenity/amenity-img/basketball_court.jpg",
  },
  {
    id: "tennis-court",
    label: "Tennis Court",
    icon: "/Amenity/amenity-icon/tennis-court.svg",
    photo: "/Amenity/amenity-img/tennis.jpg",
    img: "/Amenity/amenity-img/tennis.jpg",
  },
  {
    id: "badminton-court",
    label: "Badminton Court",
    icon: "/Amenity/amenity-icon/badminton-court.svg",
    photo: "/Amenity/amenity-img/badminton_court.jpg",
    img: "/Amenity/amenity-img/badminton_court.jpg",
  },
  {
    id: "squash-court",
    label: "Squash Court",
    icon: "/Amenity/amenity-icon/squash-court.svg",
    photo: "/Amenity/amenity-img/squash_court.jpg",
    img: "/Amenity/amenity-img/squash_court.jpg",
  },
  {
    id: "table-tennis",
    label: "Table Tennis",
    icon: "/Amenity/amenity-icon/table-tennis.svg",
    photo: "/Amenity/amenity-img/table_tennis.jpg",
    img: "/Amenity/amenity-img/table_tennis.jpg",
  },
  {
    id: "car-parking",
    label: "Car Parking",
    icon: "/Amenity/amenity-icon/car-parking.svg",
    photo: "/Amenity/amenity-img/car_parking.jpg",
    img: "/Amenity/amenity-img/car_parking.jpg",
  },
  {
    id: "ev-charging",
    label: "EV Charging",
    icon: "/Amenity/amenity-icon/ev-charging.svg",
    photo: "/Amenity/amenity-img/ev_charging.jpg",
    img: "/Amenity/amenity-img/ev_charging.jpg",
  },
  {
    id: "visitor-parking",
    label: "Visitor Parking",
    icon: "/Amenity/amenity-icon/visitor-parking.svg",
    photo: "/Amenity/amenity-img/visitor_parking.jpg",
    img: "/Amenity/amenity-img/visitor_parking.jpg",
  },
  {
    id: "bicycle-parking",
    label: "Bicycle Parking",
    icon: "/Amenity/amenity-icon/bicycle-parking.svg",
    photo: "/Amenity/amenity-img/bicycle_parking.jpg",
    img: "/Amenity/amenity-img/bicycle_parking.jpg",
  },
  {
    id: "driver-s-lounge",
    label: "Driver's Lounge",
    icon: "/Amenity/amenity-icon/driver-s-lounge.svg",
    photo: "/Amenity/amenity-img/drivers_lounge.jpg",
    img: "/Amenity/amenity-img/drivers_lounge.jpg",
  },
  {
    id: "security-room",
    label: "Security Room",
    icon: "/Amenity/amenity-icon/security-room.svg",
    photo: "/Amenity/amenity-img/security_room.jpg",
    img: "/Amenity/amenity-img/security_room.jpg",
  },
  {
    id: "reception-area",
    label: "Reception Area",
    icon: "/Amenity/amenity-icon/reception-area.svg",
    photo: "/Amenity/amenity-img/reception_area.jpg",
    img: "/Amenity/amenity-img/reception_area.jpg",
  },
  {
    id: "concierge-service",
    label: "Concierge Service",
    icon: "/Amenity/amenity-icon/concierge-service.svg",
    photo: "/Amenity/amenity-img/concierge_service.jpg",
    img: "/Amenity/amenity-img/concierge_service.jpg",
  },
  {
    id: "parcel-delivery-room",
    label: "Parcel Delivery Room",
    icon: "/Amenity/amenity-icon/parcel-delivery-room.svg",
    photo: "/Amenity/amenity-img/parcel_delivery.jpg",
    img: "/Amenity/amenity-img/parcel_delivery.jpg",
  },
  {
    id: "laundry-service",
    label: "Laundry Service",
    icon: "/Amenity/amenity-icon/laundry-service.svg",
    photo: "/Amenity/amenity-img/laundry_service.jpg",
    img: "/Amenity/amenity-img/laundry_service.jpg",
  },
  {
    id: "ev-mobility-hub",
    label: "EV Mobility Hub",
    icon: "/Amenity/amenity-icon/ev-mobility-hub.svg",
    photo: "/Amenity/amenity-img/ev_mobility_hub.jpg",
    img: "/Amenity/amenity-img/ev_mobility_hub.jpg",
  },
  {
    id: "water-feature",
    label: "Water Feature",
    icon: "/Amenity/amenity-icon/water-feature.svg",
    photo: "/Amenity/amenity-img/water_feature.jpg",
    img: "/Amenity/amenity-img/water_feature.jpg",
  },
  {
    id: "open-air-theatre",
    label: "Open Air Theatre",
    icon: "/Amenity/amenity-icon/open-air-theatre.svg",
    photo: "/Amenity/amenity-img/open_air_theatre.jpg",
    img: "/Amenity/amenity-img/open_air_theatre.jpg",
  },
];

export const amenityCategories = AMENITIES_LIST;

export const AMENITY_ICONS = Object.fromEntries(
  AMENITIES_LIST.map((item) => [item.id, item.icon])
);

export const AMENITY_PHOTOS = Object.fromEntries(
  AMENITIES_LIST.map((item) => [item.id, item.photo || item.img])
);

export function getAmenityById(id) {
  if (!id) return AMENITIES_LIST[0];
  const found = AMENITIES_LIST.find(
    (item) => item.id.toLowerCase() === id.toLowerCase()
  );
  return found || AMENITIES_LIST[0];
}

export const amenityUI = {
  loading: "Loading Amenity...",
  prevAmenities: "Previous amenities",
  scrollLeft: "Scroll left",
  nextAmenities: "Next amenities",
  scrollRight: "Scroll right",
};

export default AMENITIES_LIST;
