// Static Data & UI Labels for Inventory Page

export const inventoryUI = {
  // Brand & Media Assets
  logoSrc: "/Inventory/Riviera_logo.svg",
  logoAlt: "Riviera Select",
  buildingSrc: "/Inventory/Front_building.svg",
  buildingAlt: "Riviera Building 3D View",
  filterIconSrc: "/Inventory/Filter.svg",
  filterIconAlt: "Filter",

  // Buttons & Controls
  filterButtonText: "Filters",
  filterTitle: "Filter",
  resetFiltersText: "Reset Filters",
  collapseFilterAria: "Collapse Filters",
  wishlistAria: "Wishlist",

  // Filter Form Section Labels
  propertyTypeLabel: "Property Type",
  exposureLabel: "Exposure",
  propertyStatusLabel: "Property Status",
  areaSizeLabel: "Area Size (Sq. ft.)",

  // Slider & Input Placeholders / Units
  minPlaceholder: "Min",
  maxPlaceholder: "Max",
  sqFtUnit: "Sq.ft",
  sliderCircleSrc: "/Inventory/circle_limit.svg",

  // Unit Card Action Buttons
  viewPropertyText: "View Property",
  floorPlanText: "Floor Plan",
};

export const inventoryTableHeaders = [
  { key: "unitNo", label: "Unit No." },
  { key: "type", label: "Type" },
  { key: "exposure", label: "Exposure" },
  { key: "area", label: "Area (Sq.ft.)" },
];

export const inventoryPropertyTypes = ["Office", "Retail", "F & B", "Other"];

export const inventoryExposures = ["N", "S", "E", "W"];

export const inventoryPropertyStatuses = ["All", "Available", "Leased", "Reserved"];

export const inventoryAreaRange = {
  min: 200,
  max: 50000,
  defaultMin: 200,
  defaultMax: 50000,
  step: 100,
  minLabel: "200",
  maxLabel: "50,000",
};

export const defaultFeaturedUnit = {
  id: 6,
  unitNo: "A-801",
  type: "Duplex",
  propertyType: "Office",
  status: "Sold",
  floor: "8th Floor",
  exposure: "N,W",
  area: 2500,
  isFavorite: true,
};

export const inventoryUnits = [
  // OFFICE UNITS (IDs 1 - 20)
  {
    id: 1,
    unitNo: "A-101",
    type: "Simplex",
    propertyType: "Office",
    exposure: "N,E",
    area: 4500,
    floor: "4th Floor",
    status: "Sold",
    isFavorite: false,
  },
  {
    id: 2,
    unitNo: "A-102",
    type: "Simplex",
    propertyType: "Office",
    exposure: "S,W",
    area: 4500,
    floor: "4th Floor",
    status: "Available",
    isFavorite: false,
  },
  {
    id: 3,
    unitNo: "B-101",
    type: "Simplex",
    propertyType: "Retail",
    exposure: "W,E",
    area: 4500,
    floor: "5th Floor",
    status: "Leased",
    isFavorite: false,
  },
  {
    id: 4,
    unitNo: "B-102",
    type: "Simplex",
    propertyType: "Office",
    exposure: "N,S",
    area: 4500,
    floor: "5th Floor",
    status: "Reserved",
    isFavorite: false,
  },
  {
    id: 5,
    unitNo: "A-201",
    type: "Simplex",
    propertyType: "Office",
    exposure: "N,S",
    area: 4500,
    floor: "6th Floor",
    status: "Available",
    isFavorite: false,
  },
  {
    id: 6,
    unitNo: "A-801",
    type: "Duplex",
    propertyType: "Office",
    exposure: "N,W",
    area: 2500,
    floor: "8th Floor",
    status: "Available",
    isFavorite: true,
  },
  {
    id: 7,
    unitNo: "A-301",
    type: "Simplex",
    propertyType: "Retail",
    exposure: "N,E",
    area: 3200,
    floor: "7th Floor",
    status: "Available",
    isFavorite: false,
  },
  {
    id: 8,
    unitNo: "A-302",
    type: "Duplex",
    propertyType: "Office",
    exposure: "S,E",
    area: 4800,
    floor: "7th Floor",
    status: "Reserved",
    isFavorite: false,
  },
  {
    id: 9,
    unitNo: "B-201",
    type: "Penthouse",
    propertyType: "F & B",
    exposure: "N,S",
    area: 5500,
    floor: "9th Floor",
    status: "Available",
    isFavorite: false,
  },
  {
    id: 10,
    unitNo: "B-202",
    type: "Simplex",
    propertyType: "F & B",
    exposure: "W,S",
    area: 2800,
    floor: "9th Floor",
    status: "Leased",
    isFavorite: false,
  },
  {
    id: 11,
    unitNo: "C-101",
    type: "Studio",
    propertyType: "Retail",
    exposure: "E",
    area: 1200,
    floor: "2nd Floor",
    status: "Available",
    isFavorite: false,
  },
  {
    id: 12,
    unitNo: "C-102",
    type: "Executive",
    propertyType: "Retail",
    exposure: "N",
    area: 2100,
    floor: "2nd Floor",
    status: "Sold",
    isFavorite: false,
  },
  {
    id: 13,
    unitNo: "C-201",
    type: "Simplex",
    propertyType: "F & B",
    exposure: "S",
    area: 3500,
    floor: "3rd Floor",
    status: "Available",
    isFavorite: false,
  },
  {
    id: 14,
    unitNo: "C-202",
    type: "Duplex",
    propertyType: "Office",
    exposure: "W",
    area: 4200,
    floor: "3rd Floor",
    status: "Reserved",
    isFavorite: false,
  },
  {
    id: 15,
    unitNo: "D-301",
    type: "Penthouse",
    propertyType: "Other",
    exposure: "N,E",
    area: 6200,
    floor: "12th Floor",
    status: "Available",
    isFavorite: false,
  },
  {
    id: 16,
    unitNo: "D-302",
    type: "Simplex",
    propertyType: "Other",
    exposure: "S,W",
    area: 3800,
    floor: "12th Floor",
    status: "Leased",
    isFavorite: false,
  },
  // Additional Office Units
  {
    id: 17,
    unitNo: "A-401",
    type: "Simplex",
    propertyType: "Office",
    exposure: "E",
    area: 4100,
    floor: "8th Floor",
    status: "Available",
    isFavorite: false,
  },
  {
    id: 18,
    unitNo: "A-402",
    type: "Duplex",
    propertyType: "Office",
    exposure: "N,E",
    area: 5200,
    floor: "8th Floor",
    status: "Leased",
    isFavorite: false,
  },
  {
    id: 19,
    unitNo: "A-501",
    type: "Simplex",
    propertyType: "Office",
    exposure: "W",
    area: 3600,
    floor: "10th Floor",
    status: "Available",
    isFavorite: false,
  },
  {
    id: 20,
    unitNo: "A-502",
    type: "Duplex",
    propertyType: "Office",
    exposure: "S,W",
    area: 4900,
    floor: "10th Floor",
    status: "Reserved",
    isFavorite: false,
  },

  // RETAIL UNITS (IDs 21 - 28)
  {
    id: 21,
    unitNo: "B-301",
    type: "Simplex",
    propertyType: "Retail",
    exposure: "S",
    area: 3100,
    floor: "1st Floor",
    status: "Available",
    isFavorite: false,
  },
  {
    id: 22,
    unitNo: "B-302",
    type: "Studio",
    propertyType: "Retail",
    exposure: "S,E",
    area: 2400,
    floor: "1st Floor",
    status: "Reserved",
    isFavorite: false,
  },
  {
    id: 23,
    unitNo: "B-401",
    type: "Simplex",
    propertyType: "Retail",
    exposure: "S,W",
    area: 3700,
    floor: "2nd Floor",
    status: "Leased",
    isFavorite: false,
  },
  {
    id: 24,
    unitNo: "B-402",
    type: "Executive",
    propertyType: "Retail",
    exposure: "N,W",
    area: 2900,
    floor: "2nd Floor",
    status: "Available",
    isFavorite: false,
  },
  {
    id: 25,
    unitNo: "C-301",
    type: "Studio",
    propertyType: "Retail",
    exposure: "W",
    area: 1800,
    floor: "Ground Floor",
    status: "Available",
    isFavorite: false,
  },
  {
    id: 26,
    unitNo: "C-302",
    type: "Simplex",
    propertyType: "Retail",
    exposure: "N,S",
    area: 3300,
    floor: "Ground Floor",
    status: "Reserved",
    isFavorite: false,
  },
  {
    id: 27,
    unitNo: "C-401",
    type: "Duplex",
    propertyType: "Retail",
    exposure: "N,E",
    area: 4600,
    floor: "1st Floor",
    status: "Sold",
    isFavorite: false,
  },
  {
    id: 28,
    unitNo: "C-402",
    type: "Simplex",
    propertyType: "Retail",
    exposure: "W,E",
    area: 3900,
    floor: "2nd Floor",
    status: "Available",
    isFavorite: false,
  },

  // F & B UNITS (IDs 29 - 36)
  {
    id: 29,
    unitNo: "D-101",
    type: "Simplex",
    propertyType: "F & B",
    exposure: "N,E",
    area: 4100,
    floor: "Ground Floor",
    status: "Available",
    isFavorite: false,
  },
  {
    id: 30,
    unitNo: "D-102",
    type: "Duplex",
    propertyType: "F & B",
    exposure: "E",
    area: 5100,
    floor: "Ground Floor",
    status: "Reserved",
    isFavorite: false,
  },
  {
    id: 31,
    unitNo: "D-201",
    type: "Simplex",
    propertyType: "F & B",
    exposure: "S,E",
    area: 3600,
    floor: "1st Floor",
    status: "Leased",
    isFavorite: false,
  },
  {
    id: 32,
    unitNo: "D-202",
    type: "Studio",
    propertyType: "F & B",
    exposure: "N",
    area: 2700,
    floor: "1st Floor",
    status: "Sold",
    isFavorite: false,
  },
  {
    id: 33,
    unitNo: "E-101",
    type: "Penthouse",
    propertyType: "F & B",
    exposure: "N,W",
    area: 5800,
    floor: "Rooftop",
    status: "Available",
    isFavorite: false,
  },
  {
    id: 34,
    unitNo: "E-102",
    type: "Duplex",
    propertyType: "F & B",
    exposure: "W",
    area: 4300,
    floor: "Rooftop",
    status: "Reserved",
    isFavorite: false,
  },
  {
    id: 35,
    unitNo: "E-201",
    type: "Simplex",
    propertyType: "F & B",
    exposure: "S,W",
    area: 3900,
    floor: "3rd Floor",
    status: "Available",
    isFavorite: false,
  },
  {
    id: 36,
    unitNo: "E-202",
    type: "Executive",
    propertyType: "F & B",
    exposure: "N,S",
    area: 3400,
    floor: "3rd Floor",
    status: "Leased",
    isFavorite: false,
  },

  // OTHER UNITS (IDs 37 - 46)
  {
    id: 37,
    unitNo: "F-101",
    type: "Studio",
    propertyType: "Other",
    exposure: "N",
    area: 2200,
    floor: "11th Floor",
    status: "Available",
    isFavorite: false,
  },
  {
    id: 38,
    unitNo: "F-102",
    type: "Simplex",
    propertyType: "Other",
    exposure: "N,S",
    area: 4400,
    floor: "11th Floor",
    status: "Reserved",
    isFavorite: false,
  },
  {
    id: 39,
    unitNo: "F-201",
    type: "Duplex",
    propertyType: "Other",
    exposure: "S,E",
    area: 5300,
    floor: "12th Floor",
    status: "Sold",
    isFavorite: false,
  },
  {
    id: 40,
    unitNo: "F-202",
    type: "Executive",
    propertyType: "Other",
    exposure: "S",
    area: 3200,
    floor: "10th Floor",
    status: "Available",
    isFavorite: false,
  },
  {
    id: 41,
    unitNo: "G-101",
    type: "Simplex",
    propertyType: "Other",
    exposure: "E",
    area: 3700,
    floor: "6th Floor",
    status: "Leased",
    isFavorite: false,
  },
  {
    id: 42,
    unitNo: "G-102",
    type: "Penthouse",
    propertyType: "Other",
    exposure: "W,E",
    area: 6100,
    floor: "13th Floor",
    status: "Available",
    isFavorite: false,
  },
  {
    id: 43,
    unitNo: "G-201",
    type: "Studio",
    propertyType: "Other",
    exposure: "W",
    area: 2500,
    floor: "5th Floor",
    status: "Reserved",
    isFavorite: false,
  },
  {
    id: 44,
    unitNo: "G-202",
    type: "Duplex",
    propertyType: "Other",
    exposure: "N,W",
    area: 4700,
    floor: "7th Floor",
    status: "Available",
    isFavorite: false,
  },
  {
    id: 45,
    unitNo: "H-101",
    type: "Simplex",
    propertyType: "Other",
    exposure: "S,W",
    area: 3500,
    floor: "4th Floor",
    status: "Leased",
    isFavorite: false,
  },
  {
    id: 46,
    unitNo: "H-102",
    type: "Executive",
    propertyType: "Other",
    exposure: "N,E",
    area: 3900,
    floor: "8th Floor",
    status: "Sold",
    isFavorite: false,
  },
];
